### ISSUE TITLE
Issue finding USB based serial port

### ISSUE THREAD

**Issue by mortenboye** [ardera/linux_serial.dart#1]
Hi, is it possible to open and read from USB based serial ports?
When I attach my serial adapter, it appears in dmesg as ttyACM0, but `print("ports: ${SerialPorts.ports}");` only lists ttySxx devices.

Is there a way to make this work?

**Comment by ardera** [comment]
Was just some data missing in the magic number list
Should work now with latest master. I haven't updated the pub.dev package though, I'll do that tomorrow.

**Comment by ardera** [comment]
Oh wait, I haven't published this to pub.dev at all, my bad
